services:
  broker-service:
    build:
      context: ./../broker
      dockerfile: ./../broker/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    deploy:
      mode: replicated
      replicas: 1
  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/Dockerfile
    restart: always
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - DSN=host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5
    deploy:
      mode: replicated
      replicas: 1
  postgres:
    image: 'postgres:17.0'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data
