services:
  broker-service:
    build:
      context: ./../broker
      dockerfile: ./../broker/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    deploy:
      mode: replicated
      replicas: 1
